on: [push, pull_request]
name: Building Application
jobs:
  upload-release: 
    name: Release binary to github releases
    runs-on: [ubuntu-latest, windows-latest]
    needs: build-project
    steps:
      - name: Zipping Project
        id: zip-project
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          path: './Vulkan*'
          filename: 'release-${{ matrix.os }}.zip'
      

      - name: Create Release
        uses: actions/create-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            tag_name: ${{ github.ref }}
            release_name: Release ${{ github.ref }}
            body: |
              Última atualização do projeto!
              Versão: ${{ github.commitish }}
            draft: false
            prerelease: false

  build-project:
    strategy:
      matrix:
        go-version: [1.17]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Bulding application
      run: go build . 
      
    - uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - uses: actions/cache@v2
      with:
        # In order:
        # * Module download cache
        # * Build cache (Linux)
        # * Build cache (Mac)
        # * Build cache (Windows)
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
          ~/Library/Caches/go-build
          %LocalAppData%\go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
